### ISSUE TITLE
Morning Session Peer Review 

### ISSUE THREAD

**Issue by mertkantaroglu** [Yemisirach/JavaScript-capstone-project#26]
Hello @Yemisirach,

Good job on implementing the requirements so far. On the other hand, there might be some improvements we can suggest.

- [ ] If you can align the buttons in different cards the page will look much cleaner.
- [ ] It looks like the comment button is not working properly at the moment. Please fix it.

**Comment by Yemisirach** [comment]
Hi @mertkantaroglu 

Thank you We will fix.
